import cart from "./solar--cart-2-bold.svg"
import search from "./gravity-ui--magnifier.svg"
import ssh from "./converted_sh_logo-svg.svg"
import sh from "./Background.svg"
import xmark from "./iconoir--xmark.svg"
import arrow from "./fe--arrow-down.svg"
import pizza from "./game-icons--full-pizza.svg"
import phone from "./proicons--phone.svg"
import arow from "./arrow.svg"
import ba from "./pppp.png"
import list from "./fluent--list-24-regular.svg"
import hum from "./fluent-emoji-high-contrast--hamburger.svg"
import sla from "./game-icons--pizza-cutter.svg"
import whatsupp from "./ic--baseline-whatsapp.svg"
import linkedin from "./ri--linkedin-fill.svg"
import instagram from "./hugeicons--instagram.svg"
import facebook from "./ri--facebook-fill.svg"
import location from "./gridicons--location.svg"
export { ssh,whatsupp ,arow ,ba  , arrow ,xmark ,list ,sla ,hum ,pizza ,search ,linkedin ,instagram ,cart ,sh ,phone ,location ,facebook}
 
